name = "ticket-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "ticket-db"
database_id = "5e794ea2-fd64-4012-a68d-02192b039770"
